# Generated by Django 4.1.2 on 2022-11-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('username', models.CharField(default=None, max_length=25, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE'), ('other', 'OTHER'), ('none', 'NONE')], default=None, max_length=6)),
                ('race', models.CharField(choices=[('white', 'WHITE'), ('hispanic', 'HISPANIC'), ('black', 'BLACK'), ('asian', 'ASIAN'), ('multiple races', 'MULTIPLE RACES'), ('american indian/alaskan native', 'AMERICAN INDIAN/ALASKAN NATIVE'), ('native hawaiian/pacific islander', 'NATIVE HAWAIIAN/PACIFIC ISLANDER'), ('none', 'NONE')], default=None, max_length=33)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condition_name', models.CharField(blank=True, choices=[('diabetes', 'DIABETES'), ('hypertension', 'HYPTERTENSION'), ('cardiovasular disease', 'CARDIOVASCULAR DISEASE'), ('hyperlipidemia', 'HYPERLIPIDEMIA'), ('none', 'NONE')], default='none', max_length=32, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='dailydiary',
            fields=[
                ('dd_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kidney.client')),
            ],
            options={
                'db_table': 'dailydiary',
            },
        ),
        migrations.CreateModel(
            name='single_serving_food_item',
            fields=[
                ('food_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sodium', models.DecimalField(decimal_places=4, max_digits=20)),
                ('potassium', models.DecimalField(decimal_places=4, max_digits=20)),
                ('protein', models.DecimalField(decimal_places=4, max_digits=20)),
                ('water', models.DecimalField(decimal_places=4, max_digits=20)),
                ('phosphorus', models.DecimalField(decimal_places=4, max_digits=20)),
                ('serving_unit', models.CharField(choices=[('cup', 'CUP'), ('tablespoon', 'TABLESPOON'), ('teaspoon', 'TEASPOON'), ('grams', 'GRAMS'), ('slice', 'SLICE'), ('ounce', 'OUNCE'), ('fluid ounces', 'FLUID OUNCES'), ('liters', 'LITERS'), ('milliliters', 'MILLILITERS'), ('whole', 'WHOLE')], max_length=50)),
                ('serving_size_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'single_serving_food_item',
            },
        ),
        migrations.CreateModel(
            name='journalentry',
            fields=[
                ('journal_entry_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER'), ('snack', 'SNACK')], max_length=40)),
                ('consumed_serving_size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kidney.dailydiary')),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kidney.single_serving_food_item')),
            ],
            options={
                'db_table': 'journal_entries',
            },
        ),
    ]
