# Generated by Django 4.1.2 on 2022-11-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kidney', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='serum_entry',
            fields=[
                ('serum_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('serum_date', models.DateField()),
                ('serum_potassium', models.DecimalField(decimal_places=4, max_digits=20)),
                ('serum_phosphorus', models.DecimalField(decimal_places=4, max_digits=20)),
                ('serum_creat', models.DecimalField(decimal_places=4, max_digits=20)),
                ('serum_inine', models.DecimalField(decimal_places=4, max_digits=20)),
                ('serum_alb', models.DecimalField(decimal_places=4, max_digits=20)),
                ('serum_blood_sugar', models.DecimalField(decimal_places=4, max_digits=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kidney.client')),
            ],
        ),
    ]
