# Generated by Django 4.1.2 on 2022-11-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kidney', '0002_serum_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serum_entry',
            old_name='serum_inine',
            new_name='serum_sodium',
        ),
        migrations.AlterModelTable(
            name='serum_entry',
            table='serum_entry',
        ),
    ]
